[Icon Theme]
Name=Fonex-icons
Comment=Shall not be leaked!
Inherits=hicolor,Adwaita

Directories=scalable/actions,scalable/apps,scalable/devices,scalable/mimetypes,scalable/places

[scalable/actions]
Size=48
Context=Actions
Type=Scalable
MinSize=16
MaxSize=512

[scalable/apps]
Size=48
Context=Applications
Type=Scalable
MinSize=16
MaxSize=512

[scalable/devices]
Size=48
Context=Devices
Type=Scalable
MinSize=16
MaxSize=512

[scalable/mimetypes]
Size=48
Context=MIMETypes
Type=Scalable
MinSize=16
MaxSize=512

[scalable/places]
Size=48
Context=Places
Type=Scalable
MinSize=16
MaxSize=512